### ISSUE TITLE
Refresh / inject CSS files instead of reloading all

### ISSUE THREAD

**Issue by Elindorath** [hiddentao/gulp-server-livereload#14]
Could it be possible to not reload the entire page when only css changed? This is very annoying when you want to work your design precisely.

Thanks for the good work !

**Comment by hiddentao** [comment]
Yeah I've thought about this and it could probably be made to happen given a bit of work in the server. Perhaps the server can tell the browser which files have changed and then the browser code can decide whether to reload the whole page or not. For this to really work though, we'd need to make that code running in the browser customizable. It's a bit of work to do, and I may get round to it in future. PR always welcome.

**Comment by RomainGoncalves** [comment]
+1

**Comment by hiddentao** [comment]
I've just added support for CSS injection, see the latest README.

**Comment by hiddentao** [comment]
You shouldn't need to change your configuration settings or anything, it should just work. Also the way the script figures out the livereload server host/port etc. is now much smarter.
