### ISSUE TITLE
Compilation error on node 4.x

### ISSUE THREAD

**Issue by alexbuijs** [hiddentao/gulp-server-livereload#17]
The socket.io dependency currently fails to install on node 4.x. See https://github.com/socketio/socket.io/issues/2228

Please update and rerelease when a fix for socket.io becomes available. In the mean time https://github.com/alexbuijs/gulp-server-livereload could be used which contains this repo: https://github.com/pmq20/socket.io

**Comment by hiddentao** [comment]
Thanks for letting us know.

**Comment by hiddentao** [comment]
Still seeing this?

**Comment by alexbuijs** [comment]
No, has been fixed!
