### ISSUE TITLE
specify launch domain setting request

### ISSUE THREAD

**Issue by landed1** [hiddentao/gulp-server-livereload#18]
I am trying to do something like this as locally the 0.0.0.0 address will fail - localhost works but i want to kind of launch right into local though setting 0.0.0.0 so I can browse across the DOMAIN network on my device...

.pipe(server({
      livereload: true,
      directoryListing: false,
      open: true,
      host:'0.0.0.0',
      defaultFile: 'localhost:8000/index.html'
    }));
});

**Comment by hiddentao** [comment]
0.0.0.0 should definitely work, I've been using that myself for a while.

**Comment by landed1** [comment]
Thanks.
