### ISSUE TITLE
Cannot create a second instance of Gulp Server Livereload if the first instance has livereload in true.

### ISSUE THREAD

**Issue by sant123** [hiddentao/gulp-server-livereload#19]
Hi, as the title says if I make an instance of gulp-server-livereload with option `livereload: true`, the second instance will not support it and will throw an error. I think this was not planned because it would create a second socket in the browser, however, a user would work in multiple projects with livereload. The error is the following...

![gslr_error](https://cloud.githubusercontent.com/assets/7959437/10496964/efac8f88-7288-11e5-9dfe-4f7594f600ee.PNG)

I'm using gulp-json-srv as well, I just commented it and it happens the same. Here is my code:

![gslr_error1](https://cloud.githubusercontent.com/assets/7959437/10496987/1d0a0578-7289-11e5-89f6-fd8991fc807d.PNG)

Thanks!.

**Comment by hiddentao** [comment]
You can specify both the webserver and livereload ports in your configs. If you don't do this it will use default port numbers, which is why you're getting the "already in use" errors.
