### ISSUE TITLE
LIVERELOAD: unable to find server address

### ISSUE THREAD

**Issue by vzhen** [hiddentao/gulp-server-livereload#20]
As title.

I have no idea why my livereload now coming with this error. This error happens when I CTRL+S and i need to press F5 browser refresh to resolve this error.

Windows 7 64bits with latest chrome

**Comment by hiddentao** [comment]
Need more info, what console errors are you seeing. Have you tried it with the latest version?

**Comment by hiddentao** [comment]
Should be resolved now.
