### ISSUE TITLE
Access-Control-Allow-Origin' header is missing

### ISSUE THREAD

**Issue by povilas0** [hiddentao/gulp-server-livereload#26]
I am using 1.6.0 version of this plugin.

Usage of the plugin in **gulpfile** looks like this:
`gulp.src("dist")
    .pipe(server({
      livereload: true,
      open: true
    }));`

And I am getting these errors:
`XMLHttpRequest cannot load http://localhost:35729/socket.io/?EIO=3&transport=polling&t=L9QRZG-. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access. The response had HTTP status code 404.`

Is there anything missing in my gulpfile?

**Comment by hiddentao** [comment]
Thanks for spotting this, it's now fixed in 1.6.1.
