### ISSUE TITLE
Simply no longer working

### ISSUE THREAD

**Issue by landed1** [hiddentao/gulp-server-livereload#29]
This was the best IMO live reloading server for gulp ! I think since I updated npm locally to...3.7.2 or some other reason its showing just a directory listing but wont serve any page or file I get the error 
Cannot GET /dist/index.html

**Comment by hiddentao** [comment]
Hmm what are your config options?

**Comment by landed1** [comment]
they were minimal and all kinds of tests in between. Have you tried with the latest npm ?
It does work setting a fallback however then every file falls back to this file.

**Comment by hiddentao** [comment]
Just tested this myself with the latest (1.7.0) and it works fine for me. It serves up files both in the root folder as well as subfolders.

**Comment by landed1** [comment]
ok thanks for that. I am at a loss.
