### ISSUE TITLE
Cannot serve custom expressjs app.

### ISSUE THREAD

**Issue by ianjosephwilson** [hiddentao/gulp-server-livereload#3]
Is it possible to extend this so that a custom express app could be specified rather than using a fixed server that just serves static assets?  The majority of the app is js/css/html but there are a few dynamic routes that are not served when just serving the js/css/html directly.

**Comment by hiddentao** [comment]
So basically you'd like to implement livereload into your custom app? You might be better off integrating the socket.io system directly into your app in that case.

**Comment by hiddentao** [comment]
Note that a proxy system is currently on the way -> #8

**Comment by hiddentao** [comment]
Proxy system is in.
