### ISSUE TITLE
Extend logging ability to allow hiding "file changed" and "client connected" messages.

### ISSUE THREAD

**Issue by SteffanDonal** [hiddentao/gulp-server-livereload#36]
I'd quite like to be able to set other logging levels, to be able to reduce console noise whilst developing.

What are your thoughts? Happy to write the code for this and submit a pull request.

**Comment by hiddentao** [comment]
Yes please do, would love to see your approach to this.

**Comment by devonsams** [comment]
I'm using with babel, and when there are compile errors, they instantly get buried under "file changed" and "client connected" messages. So this would be very handy for me.

**Comment by SteffanDonal** [comment]
I'm starting development of this now!

**Comment by SteffanDonal** [comment]
Implemented in #41!

Notes:  
- `clientLog` is a new option that allows for independent filtering of client logging. Handy for making sure that client logging continues to come through even if the server's logging is set to `error`.
- Livereload client logging (connected messages, errors, etc) has been restricted to the client console. to help keep the console readable.
