### ISSUE TITLE
how to define rule when fallback should work?

### ISSUE THREAD

**Issue by aafeltowicz** [hiddentao/gulp-server-livereload#37]
Is it possible out of the box to define rule when fallback should work?

What I want to achieve is to handle angular routes (SPA without hashbang) with fallback mechanism, but for missing static files I want to receive HTTP 404.

**Comment by hiddentao** [comment]
No support out of the box at the moment. But it sounds like a good idea. PR welcome.

**Comment by aafeltowicz** [comment]
Please find in attachment fix for my case.

[no_fallback_for_static_files.zip](https://github.com/hiddentao/gulp-server-livereload/files/374441/no_fallback_for_static_files.zip)

**Comment by aafeltowicz** [comment]
Any chance to commit changes and release new version?

**Comment by hiddentao** [comment]
If you could do it as a PR will be happy to include it. That way I will also be able to give feedback and we will be able to iterate on it if necessary.

**Comment by aafeltowicz** [comment]
Ok, my bad - sorry, I'm new to GitHub. PR done.

**Comment by aafeltowicz** [comment]
Thanks for merge. I've noticed that options table - (https://github.com/hiddentao/gulp-server-livereload#options) has broken after adding fallbackLogic param description.

**Comment by hiddentao** [comment]
Thanks, now fixed.

-- 
Ramesh Nair

Director
HiddenTao Ltd (UK company no. 6807289)

http://hiddentao.com
https://github.com/hiddentao
https://www.linkedin.com/in/hiddentao

On 27 July 2016 at 11:56:07, aafeltowicz (notifications@github.com) wrote:

Thanks for merge. I've noticed that options table - (https://github.com/hiddentao/gulp-server-livereload#options) has broken after adding fallbackLogic param description.
