### ISSUE TITLE
Filter livereload files

### ISSUE THREAD

**Issue by ppkn** [hiddentao/gulp-server-livereload#7]
Is it possible to ignore some files that the socket.io livereload catches?

**Comment by hiddentao** [comment]
Yep this would be possible though would require some coding to enable. Would welcome a PR.

**Comment by ppkn** [comment]
Where is a good place to start looking in the code?

**Comment by hiddentao** [comment]
This line does the watching -> https://github.com/hiddentao/gulp-server-livereload/blob/master/src/index.js#L221

**Comment by hiddentao** [comment]
The `livereload.filter` option satisfies this now.
